trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - '*'

pool:
  name: Pauli

steps:
  - checkout: self

  - task: UseDotNet@2
    displayName: 'Setup .NET 8'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - task: NodeTool@0
    displayName: 'Setup Node.js 20'
    inputs:
      versionSpec: '20.x'

  - script: dotnet restore ProductApi.sln
    displayName: 'Restore .NET'
    workingDirectory: Backend

  - script: dotnet build ProductApi.sln --configuration Debug --no-restore
    displayName: 'Build .NET'
    workingDirectory: Backend

  - script: >-
      dotnet test --configuration Debug
      --logger "trx;LogFileName=dotnet-tests.trx"
      --collect:"XPlat Code Coverage"
      --results-directory "$(Build.SourcesDirectory)/test-results"
    displayName: 'Test .NET'
    workingDirectory: Backend.Tests

  - task: PublishTestResults@2
    displayName: 'Publish .NET Test Results'
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'test-results/*.trx'
      searchFolder: '$(Build.SourcesDirectory)'
      testRunTitle: '.NET Tests'
      mergeTestResults: true
      failTaskOnFailedTests: true

  - script: npm ci
    displayName: 'Install Angular deps'
    workingDirectory: Frontend

  - task: Cache@2
    displayName: 'Cache Angular build cache (.angular/cache)'
    inputs:
      key: 'angular-cache | $(Agent.OS) | "$(Build.SourcesDirectory)/Frontend/package-lock.json"'
      restoreKeys: 'angular-cache | $(Agent.OS) |'
      path: '$(Build.SourcesDirectory)/Frontend/.angular/cache'

  - script: npm run test:coverage --silent
    displayName: 'Test Angular (headless)'
    workingDirectory: Frontend

  - task: PublishTestResults@2
    displayName: 'Publish Angular JUnit'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'Frontend/test-results/*.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Angular Coverage HTML'
    inputs:
      PathtoPublish: 'Frontend/coverage'
      ArtifactName: 'angular-coverage'
      publishLocation: 'Container'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish .NET Coverage (raw)'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/test-results'
      ArtifactName: 'dotnet-test-results'
      publishLocation: 'Container'
